---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/basic_health_units":
    get:
      summary: list basic_health_units
      responses:
        '200':
          description: successful
    post:
      summary: create basic_health_unit
      parameters: []
      responses:
        '200':
          description: successful
  "/api/v1/basic_health_units/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show basic_health_unit
      responses:
        '200':
          description: successful
    patch:
      summary: update basic_health_unit
      responses:
        '200':
          description: successful
    put:
      summary: update basic_health_unit
      parameters: []
      responses:
        '200':
          description: successful
    delete:
      summary: delete basic_health_unit
      responses:
        '200':
          description: successful
  "/api/v1/find_ubs":
    parameters:
    - name: query
      in: query
      description: query
      required: true
      schema:
        type: string
    - name: range
      in: query
      description: range
      required: false
      schema:
        type: string
    - name: page
      in: query
      description: page
      required: false
      schema:
        type: string
    - name: per_page
      in: query
      description: per_page
      required: false
      schema:
        type: string
    get:
      summary: find_ubs basic_health_unit
      responses:
        '200':
          description: successful
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
