default: &default
  adapter: postgresql
  encoding: utf8
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: bio_development


test:
  <<: *default
  database: bio_test